credentials:
  atlas: nvdbapil-atlas
  git: apnevegdata.admin
  artifactory: artrepo
  refreshToken: refreshToken-Nvdbapil
releaseBranch: main
iktlosning: nvdbapil
environments:
  main: utv-1
slackChannel: digital-drivkraft-pr
repository: nvdb-finn-vegdata
